VL.ItsMe1110/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using VL.Common.Core.Object.VL.Blog;
using VL.Common.Core.Protocol;
using VL.ItsMe1110.Custom.Authentications;
using VL.ItsMe1110.Models;

namespace VL.ItsMe1110.Controllers
{
    public partial class BlogController : BaseController
    {
        #region ObjectBlogServiceClient
        private ObjectBlogService.ObjectBlogServiceClient _ObjectBlogClient;
        public ObjectBlogService.ObjectBlogServiceClient ObjectBlogClient
        {
            get
            {
                if (_ObjectBlogClient == null)
                {
                    _ObjectBlogClient = new ObjectBlogService.ObjectBlogServiceClient();
                }
                return _ObjectBlogClient;
            }
        }
        #endregion
        #region SubjectBlogServiceClient
        private SubjectBlogService.SubjectBlogServiceClient _subjectBlogClient;
        public SubjectBlogService.SubjectBlogServiceClient SubjectBlogClient
        {
            get
            {
                if (_subjectBlogClient == null)
                {
                    _subjectBlogClient = new SubjectBlogService.SubjectBlogServiceClient();
                }
                return _subjectBlogClient;
            }
        }
        #endregion

        #region 管理
        [HttpGet]
        [VLAuthorize(Users = VESTEDUSERSTRING)]
        public ActionResult Index()
        {
            var blogs = ObjectBlogClient.GetAllBlogs();
            var model = new BlogListModel();
            foreach (var blog in blogs.Data)
            {
                model.Add(new BlogListItem()
                {
                    BlogId = blog.BlogId,
                    Title = blog.Title,
                    BreviaryContent = blog.BreviaryContent,
                    CreatedTime = blog.CreatedTime,
                    LastEditTime = blog.LastEditTime,
                    IsVisible = blog.IsVisible,
                });
            }
            return View(model);
        }

        [HttpGet]
        [VLAuthorize(Users = VESTEDUSERSTRING)]
        public async Task<ActionResult> Edit(Guid id, string title)
        {
            if (id == Guid.Empty)
            {
                return View(new BlogEditModel() { BlogId = id });
            }

            var result = new BlogEditModel() { BlogId = id, Title = title };
            var detailTask = ObjectBlogClient.GetBlogDetailAsync(id);
            var tagTask = ObjectBlogClient.GetBlogTagsAsync(id);
            var detailResult = await detailTask;
            if (detailResult.Code == CProtocol.CReport.CSuccess)
            {
                result.Content = detailResult.Data.Content;
            }
            else
            {
                ModelState.AddModelError("", "加载Detail内容出错");
            }
            var tagResult = await tagTask;
            if (tagResult.Code == CProtocol.CReport.CSuccess)
            {
                result.StartTags = string.Join(",", tagResult.Data.Select(c=>c.TagName));
                result.EndTags = result.StartTags;
            }
            else
            {
                ModelState.AddModelError("", "加载Detail内容出错");
            }
            return View(result);
        }
        [HttpPost]
        [VLAuthorize(Users = VESTEDUSERSTRING)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(BlogEditModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var startTags = model.StartTags == null ? new List<string>() : model.StartTags.Split(',').ToList();
            startTags.RemoveAll(c => c == "");
            var endTags = model.EndTags == null ? new List<string>() : model.EndTags.Split(',').ToList();
            endTags.RemoveAll(c => c == "");
            var addTags = endTags.Where(c => !startTags.Contains(c)).ToList();
            var deleteTags = startTags.Where(c => !endTags.Contains(c)).ToList();
            var result = await SubjectBlogClient.EditBlogAsync(new TBlog() { BlogId = model.BlogId, UserName = User.Identity.Name, Title = model.Title }, model.Content, addTags, deleteTags);
            if (result.Code == CProtocol.CReport.CSuccess)
            {
                return RedirectToAction(nameof(BlogController.Index), PAGENAME_BLOG);
            }
            else
            {
                AddMessages(result.Code, new KeyValueCollection {
                            new KeyValue(2, "系统内部异常") ,
                            new KeyValue(11, "用户名不可为空") ,
                            new KeyValue(12, "标题不可为空") ,
                            new KeyValue(13, "内容不可为空") ,
                            new KeyValue(14, "内容新建失败") ,
                            new KeyValue(15, "主体新建失败") ,
                            new KeyValue(16, "内容更新失败") ,
                            new KeyValue(17, "主体更新失败") ,
                            new KeyValue(18, "标签新建失败") ,
                            new KeyValue(19, "标签删除失败") ,
                            new KeyValue(20, "关联加载失败") ,
                            new KeyValue(21, "关联新建失败") ,
                            new KeyValue(22, "关联删除失败") ,
                        });

                return View(model);
            }
        }

        [HttpPost]
        [VLAuthorize(Users = VESTEDUSERSTRING)]
        public async Task<bool> ChangeVisibility(Guid id, bool isVisible)
        {
            var result = await SubjectBlogClient.ChangeVisibilityAsync(id, isVisible);
            if (result.Code != CProtocol.CReport.CSuccess)
            {
                return false;
            }
            return true;
        }
        #endregion

        #region 游客
        [HttpGet]
        public async Task<ActionResult> List()
        {
            var result = await ObjectBlogClient.GetVisibleBlogsAsync();
            if (result.Code != CProtocol.CReport.CSuccess)
            {
            }
            var model = new BlogListModel();
            foreach (var blog in result.Data)
            {
                model.Add(new BlogListItem()
                {
                    BlogId = blog.BlogId,
                    Title = blog.Title,
                    BreviaryContent = blog.BreviaryContent,
                    CreatedTime = blog.CreatedTime,
                    LastEditTime = blog.LastEditTime,
                    IsVisible = blog.IsVisible,
                });
            }
            return View(model);
        }
        [HttpGet]
        public async Task<ActionResult> Detail(Guid id)
        {
            if (id == Guid.Empty)
            {
                ModelState.AddModelError("", "文章Id不可为空");
                return View(new BlogDetailModel() { BlogId = id });
            }

            var getDBodyTask = ObjectBlogClient.GetBlogBodyAsync(id);
            var getDetailTask = ObjectBlogClient.GetBlogDetailAsync(id);
            var model = new BlogDetailModel();
            model.BlogId = id;
            var bodyResult = await getDBodyTask;
            if (bodyResult.Code == CProtocol.CReport.CSuccess)
            {
                model.Title = bodyResult.Data.Title;
                model.CreatedTime = bodyResult.Data.CreatedTime;
                model.LastEditTime = bodyResult.Data.LastEditTime;
                model.UserName = bodyResult.Data.UserName;
            }
            else
            {
                ModelState.AddModelError("", "加载Body内容出错");
            }
            var detailResult = await getDetailTask;
            if (detailResult.Code == CProtocol.CReport.CSuccess)
            {
                model.Content = detailResult.Data.Content;
            }
            else
            {
                ModelState.AddModelError("", "加载Detail内容出错");
            }
            return View(model);
        }
        #endregion

        #region 用户

        #endregion
    }
}

VL.ItsMe1110/Controllers/HomeController.cs
using System.Web.Mvc;
using VL.ItsMe1110.Controllers;

namespace VL.ItsMe1110.Controllers
{
    public class HomeController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        [HttpGet]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

VL.ItsMe1110/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

VL.ItsMe1110/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    <abbr title="Phone">P:</abbr>
    15158131226
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:vlong638@163.com">vlong638@163.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:vlong638@163.com">vlong638@163.com</a>
</address>

VL.ItsMe1110/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>简介</h1>
    <p class="lead">
        欢迎来到vlong638的国度<br />
        这里有我制作的一些作品实例<br />
    </p>
    <p>
        @Html.ActionLink("我的博客 >", "List", "Blog", null, new { @class = "btn btn-primary btn-lg" })
        @Html.ActionLink("我的独立游戏 >", "List", "Blog", null, new { @class = "btn btn-primary btn-lg" })
        @Html.ActionLink("她的博客 >", "List", "Blog", null, new { @class = "btn btn-primary btn-lg" })
        @Html.ActionLink("她的地盘 >", "List", "Blog", null, new { @class = "btn btn-primary btn-lg" })
    </p>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>